username: GitHubXGc
baseurl: /bystanford
markdown: redcarpet
safe: false
highlighter: pygments
title: onmywaying
description: 不困于情，不畏于心
theme: modernist
disqusname: minixalpha

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
